/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kys_deneme1;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author user
 */
public class MainProgram extends javax.swing.JFrame {

    /**
     * Creates new form MainProgram
     */
    
    private String userID;
    DB db = new DB();
    JTable articleTable;
    private String articleID;
    DefaultListModel<String> listModel = new DefaultListModel<String>(); //
    int [] indices = new int[3];
    ArrayList<String> reviewerID = new ArrayList<String>();
    int reviewer1;
    int reviewer2;
    int reviewer3;
    ArrayList<String> reviewerSelectedArticleID = new ArrayList<String>();
    ArrayList <String> arIDs;
    
    
    public MainProgram() {
        initComponents(); 
        SetUserID(userID);
    }
    
    public MainProgram(String userID) throws SQLException{
        initComponents();
        setLocationRelativeTo(null);
        SetUserID(userID);
        
        
        // CHECK USER TYPE and NAME HERE
        db.OpenConnection(); //open db connection
        String userType=db.CheckUserType(GetUserID()); //check user email an return its type
        String userName=db.GetNameUserTypeCheck(); // get user name
        /*System.out.println(userType); //test
        System.out.println(userName);*/ //test
        db.CloseDB();
        
        userNameLabel.setText(userName);
        
        if (userType.equals("Hakem")){
            //hakem giriş yaptı
            System.out.println("Hakem girdi");
            userTypePane.removeTabAt(2); //remove tab OKB
            
            //puan verilecek item'lar yüklenir
            listModel.clear();
            db.OpenConnection();
            db.ArticlesToBeScored(userID,listModel); //kullanıcıya göre listmodele verileri ata
            
            reviewerSelectedArticleID=db.GetSelectedArticleID();
            System.out.println(reviewerSelectedArticleID); //hakemin seçtiği article idlerini al*/
            
            articleReviewList.setModel(listModel);
            
            db.CloseDB();
            
        }else if(userType.equals("admin")){
            //okb giriş yaptı
            System.out.println("OKB girdi");
            userTypePane.removeTabAt(0);//remove tab author
            userTypePane.removeTabAt(0);//remove tab reviewer
            
            db.OpenConnection();            
            db.ArticleList(articleTitleCombo);//retreive article titles from DB
            db.CloseDB();
            
        }else{
            // yazar giriş yaptı
            System.out.println("Yazar girdi");
            userTypePane.removeTabAt(1); //remove tab reviewer
            userTypePane.removeTabAt(1); //remove tab OKB
            
        }
        
        LoadResults();
       
        
    }
    
    
    
   public void SetUserID(String userID){
        this.userID=userID;
    }
    public String GetUserID(){
        return userID;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userTypePane = new javax.swing.JTabbedPane();
        userTypePanel = new javax.swing.JPanel();
        authorMenu = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        entryComboBox = new javax.swing.JComboBox();
        avgTxt = new javax.swing.JTextField();
        resutlTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        articleText = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        authors = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        summary = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        keywords = new javax.swing.JTextField();
        subject = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        submitArticle = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        articleReviewList = new javax.swing.JList();
        readEvaluateButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        shuffleReviewersButton = new javax.swing.JButton();
        articleTitleCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        reviewerList = new javax.swing.JList();
        jLabel14 = new javax.swing.JLabel();
        articleAuthors = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        articleSummary = new javax.swing.JTextArea();
        articleSubject = new javax.swing.JTextField();
        submitArticleToReviewers = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conference Management System: Main Program");

        jLabel16.setText("My Entries :");

        jLabel17.setText("Average Score :");

        jLabel18.setText("Result :");

        entryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select an Entry" }));
        entryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                entryComboBoxİtemStateChanged(evt);
            }
        });

        avgTxt.setEditable(false);

        resutlTxt.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(entryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resutlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(entryComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avgTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resutlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        authorMenu.addTab("Current Entries", jScrollPane1);

        jLabel2.setText("Article's Title :");

        articleText.setColumns(20);
        articleText.setRows(5);
        jScrollPane3.setViewportView(articleText);

        jLabel3.setText("Article :");

        jLabel4.setText("Authors :");

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("* Please use comma between authors, if there are more than one.");

        jLabel6.setText("E-mail for contact :");

        jLabel8.setText("Summary :");

        summary.setColumns(20);
        summary.setRows(5);
        jScrollPane4.setViewportView(summary);

        jLabel9.setText("Keywords :");

        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        jLabel10.setText("Subject :");

        submitArticle.setText("Submit");
        submitArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitArticleActionPerformed(evt);
            }
        });

        clearButton.setText("Clear Fields");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                            .addComponent(title)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(submitArticle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(clearButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subject, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(keywords, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(contact, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(authors)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(authors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keywords, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitArticle)
                    .addComponent(clearButton))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        authorMenu.addTab("Send Article", jScrollPane2);

        javax.swing.GroupLayout userTypePanelLayout = new javax.swing.GroupLayout(userTypePanel);
        userTypePanel.setLayout(userTypePanelLayout);
        userTypePanelLayout.setHorizontalGroup(
            userTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        userTypePanelLayout.setVerticalGroup(
            userTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTypePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authorMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        userTypePane.addTab("Author", userTypePanel);

        articleReviewList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(articleReviewList);

        readEvaluateButton.setText("Read and Evaluate Article");
        readEvaluateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readEvaluateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(readEvaluateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(readEvaluateButton)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        userTypePane.addTab("Reviewer", jPanel2);

        shuffleReviewersButton.setText("Shuffle Reviewers");
        shuffleReviewersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleReviewersButtonActionPerformed(evt);
            }
        });

        articleTitleCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Please Select an Article" }));
        articleTitleCombo.setToolTipText("");
        articleTitleCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                articleTitleComboİtemStateChanged(evt);
            }
        });

        jLabel7.setText("Article Title");

        jLabel11.setText("Article Authors");

        jLabel12.setText("Article Summary");

        jLabel13.setText("Article Subject");

        reviewerList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                reviewerListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(reviewerList);

        jLabel14.setText("Reviewers");

        articleAuthors.setEditable(false);

        articleSummary.setEditable(false);
        articleSummary.setColumns(20);
        articleSummary.setLineWrap(true);
        articleSummary.setRows(5);
        jScrollPane6.setViewportView(articleSummary);

        articleSubject.setEditable(false);

        submitArticleToReviewers.setText("Submit Reviewers");
        submitArticleToReviewers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitArticleToReviewersActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Use combination CTRL + Mouse Click to select multiple reviewers manually.");

        jButton1.setText("Show Article Scores");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(articleTitleCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(articleAuthors, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(shuffleReviewersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitArticleToReviewers, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(articleSubject)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(articleTitleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(articleAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(articleSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shuffleReviewersButton)
                    .addComponent(submitArticleToReviewers))
                .addGap(34, 34, 34))
        );

        userTypePane.addTab("OKB", jPanel4);

        jLabel1.setText("Welcome,");

        userNameLabel.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userTypePane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTypePane, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        //clear input fields
                title.setText("");
                articleText.setText("");
                authors.setText("");
                contact.setText("");
                summary.setText("");
                keywords.setText("");
                subject.setText("");//end of clear
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void submitArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitArticleActionPerformed
        // TODO add your handling code here:
        Article ar = new Article ();        
        
        /*
        System.out.println(title.getText());
        System.out.println(articleText.getText());
        System.out.println(authors.getText());
        System.out.println(contact.getText());
        System.out.println(summary.getText());
        System.out.println(keywords.getText());
        System.out.println(subject.getText());*/
        
        if(!title.getText().isEmpty() && !articleText.getText().isEmpty() && !authors.getText().isEmpty()&&
                !contact.getText().isEmpty() && !summary.getText().isEmpty() && 
                !keywords.getText().isEmpty() && !subject.getText().isEmpty()){
        
        //set
        try{
            ar.SetTitle(title.getText());
            ar.SetArticleText(articleText.getText());
            ar.SetAuthors(authors.getText());
            ar.SetContact(contact.getText());
            ar.SetSummary(summary.getText());
            ar.SetKeywords(keywords.getText());
            ar.SetSubject(subject.getText());
            
            db.OpenConnection();
            
            //send values to database class associated method if true returns clear fields
            boolean recordSuccess = db.RecordArticle(GetUserID(),ar.GetTitle(), ar.GetArticleText(), 
                ar.GetAuthors(), ar.GetContact(), ar.GetSummary(), ar.GetKeywords(), ar.GetSubject());    
            
            if(recordSuccess){
                db.CloseDB();
                //clear input fields
                title.setText("");
                articleText.setText("");
                authors.setText("");
                contact.setText("");
                summary.setText("");
                keywords.setText("");
                subject.setText("");//end of clear
            }
        }catch(Exception e){
            db.CloseDB();
            System.out.println("Error : "+ e.getMessage());
            JOptionPane.showMessageDialog(null,"Registiration is unsuccesful!");
            
        }
        }
        else{
            //fields cannot be empty
            JOptionPane.showMessageDialog(null,"Registiration is unsuccesful! Fields can not be empty!");
        }
        
        
    }//GEN-LAST:event_submitArticleActionPerformed

    private void articleTitleComboİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_articleTitleComboİtemStateChanged
        // TODO add your handling code here:
        Object articleTitleItem = articleTitleCombo.getSelectedItem();
        System.out.println(articleTitleItem.toString());
        
        
        /*GET ARTICLE ID*/
        db.OpenConnection();
        articleID=db.GetArticleID(articleTitleItem.toString()); // GET ARTICLE ID
        
        //FULFILL FIELDS VIA ARTICLE ID
        db.FulfillArticleInfo(articleID);
        articleAuthors.setText(db.GetArticleAuthors()); //set textfields
        articleSummary.setText(db.GetArticleSummary());
        articleSubject.setText(db.GetArticleSubject());
        
        System.out.println("Yazar: "+db.GetArticleUserID());
        
        //FULFILL REVIEWERS
        
        listModel.clear();
        reviewerID.clear();
        
        //listModel.addElement();
        db.FulfillAuthors(db.GetArticleSubject(), db.GetArticleUserID(),listModel,reviewerID);
        
        reviewerList.setModel(listModel);//set JList with listModel
        //take reviewer ID
        for(int i=0;i<reviewerID.size();i++){
            System.out.println(reviewerID.get(i));
        }
        
        db.CloseDB();
    }//GEN-LAST:event_articleTitleComboİtemStateChanged

    private void shuffleReviewersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleReviewersButtonActionPerformed
        // TODO add your handling code here:
        try{
        int length = reviewerList.getModel().getSize();
        Random random = new Random();
        reviewer1=random.nextInt(length);
        reviewer2=random.nextInt(length);
        reviewer3=random.nextInt(length);
        
        //check if randomly allocated values are equal to each
        while(reviewer1==reviewer2 || reviewer1==reviewer3){
            reviewer1=random.nextInt(length);
        }
        while(reviewer2==reviewer1 || reviewer2==reviewer3){
            reviewer2=random.nextInt(length);
        }
        //end of check
        
        indices = new int[]{reviewer1, reviewer2, reviewer3};
        reviewerList.setSelectedIndices(indices);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"You should choose an article first! "+ ex.getMessage());
        }
    }//GEN-LAST:event_shuffleReviewersButtonActionPerformed

    private void reviewerListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_reviewerListValueChanged
        // TODO add your handling code here:
        //LIMIT TO SELECT ONLY 3 REVIEWERS
        
        
        
    }//GEN-LAST:event_reviewerListValueChanged

    private void submitArticleToReviewersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitArticleToReviewersActionPerformed
        // TODO add your handling code here:
        try{
        db.OpenConnection();
        db.InsertReviewersAndArticleDB(articleID,reviewerID.get(reviewerList.getSelectedIndices()[0]),
                reviewerID.get(reviewerList.getSelectedIndices()[1]),
                reviewerID.get(reviewerList.getSelectedIndices()[2]));
        db.CloseDB();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this,"You should choose 3 reviewers only! "+ ex.getMessage());
        }
    }//GEN-LAST:event_submitArticleToReviewersActionPerformed

    public void LoadResults(){
       
       arIDs=new ArrayList <String>();
       db.OpenConnection();
       arIDs=db.FulFillUserEntries(GetUserID());
       System.out.println(arIDs);
       for (int i =0; i<arIDs.size(); i++){
           entryComboBox.addItem(arIDs.get(i));
       }
       db.CloseDB();
       
    }
    
    private void readEvaluateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readEvaluateButtonActionPerformed
        // TODO add your handling code here:
        //GET SELECTED ARTICLE ID TO BE SCORED BY REVIEWER
        int index = articleReviewList.getSelectedIndex();
        System.out.println(index);
        System.out.println(reviewerSelectedArticleID.get(index)); //SELECTED ARTICLE ID TO BE SCORED
        
        EvaluateArticle ea;
        ea = new EvaluateArticle(GetUserID(),reviewerSelectedArticleID.get(index));
        ea.setVisible(true);
        ea.pack();
        ea.setLocationRelativeTo(null);
        ea.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_readEvaluateButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ArticleScoresOKB as;
        as = new ArticleScoresOKB (GetUserID());
        as.setVisible(true);
        as.pack();
        as.setLocationRelativeTo(null);
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void entryComboBoxİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_entryComboBoxİtemStateChanged
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_entryComboBoxİtemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainProgram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainProgram().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField articleAuthors;
    private javax.swing.JList articleReviewList;
    private javax.swing.JTextField articleSubject;
    private javax.swing.JTextArea articleSummary;
    private javax.swing.JTextArea articleText;
    private javax.swing.JComboBox articleTitleCombo;
    private javax.swing.JTabbedPane authorMenu;
    private javax.swing.JTextField authors;
    private javax.swing.JTextField avgTxt;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox entryComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField keywords;
    private javax.swing.JButton readEvaluateButton;
    private javax.swing.JTextField resutlTxt;
    private javax.swing.JList reviewerList;
    private javax.swing.JButton shuffleReviewersButton;
    private javax.swing.JTextField subject;
    private javax.swing.JButton submitArticle;
    private javax.swing.JButton submitArticleToReviewers;
    private javax.swing.JTextArea summary;
    private javax.swing.JTextField title;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTabbedPane userTypePane;
    private javax.swing.JPanel userTypePanel;
    // End of variables declaration//GEN-END:variables
}
